//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int? Id { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public bool Sexo { get; set; }
        public int EstadoNacimiento { get; set; }
        public long Telefono { get; set; }
        public int Estado { get; set; }
        public string Municipio { get; set; }
        public string Colonia { get; set; }
        public string CalleNumero { get; set; }
        public Nullable<bool> activo { get; set; }
        public string CURP { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual Estado Estado2 { get; set; }
    }
}
